#!/bin/bash

# Regenerate executables and run the benchmarks.

# Record if the executables already existed
main_existed=false
main2_existed=false
benchmark_existed=false

# Delete the two executables if they exist
if [ -f main ]; then
    main_existed=true
    rm main
fi

if [ -f main2 ]; then
    main2_existed=true
    rm main2
fi

if [ -f benchmark ]; then
    benchmark_existed=true
    rm benchmark
fi

# Regenerate them
gcc -O3 -fopenmp -flto -ftree-vectorize -m64 -march=native main.c -o main
if [ $? -ne 0 ]; then
    echo "Failed to compile main.c"
    exit 1
fi

gcc -O3 -fopenmp -flto -ftree-vectorize -m64 -march=native main.c -o main
if [ $? -ne 0 ]; then
    echo "Failed to compile main2.c"
    exit 1
fi


gcc -O3 benchmark.c -o benchmark
if [ $? -ne 0 ]; then
    echo "Failed to compile benchmark.c"
    exit 1
fi

# Execute the benchmark file
./benchmark
if [ $? -ne 0 ]; then
    echo "Benchmark execution failed"
    exit 1
fi

# Clean up the executables if they didn't already exist
if [ "$main_existed" = false ]; then
    rm main
fi

if [ "$main2_existed" = false ]; then
    rm main2
fi

if [ "$benchmark_existed" = false ]; then
    rm benchmark
fi